language: minimal
dist: bionic
cache:
  apt: true
  timeout: 1000 #In seconds
  directories:
  - $TRAVIS_BUILD_DIR/riscv64
  - $TRAVIS_BUILD_DIR/linux/.git
  - $TRAVIS_BUILD_DIR/qemu/.git

git:
  submodules: false
  depth: 1

env:
  - RISCV=$TRAVIS_BUILD_DIR/riscv64 PATH=$PATH:$RISCV/bin

addons:
  apt:
    packages:
    - expect
    - autoconf
    - automake
    - autotools-dev
    - bc
    - bison
    - build-essential
    - curl
    - expat
    - libexpat-dev
    - flex
    - gawk
    - gcc
    - git
    - gperf
    - libgmp-dev
    - libmpc-dev
    - libmpfr-dev
    - libtool
    - texinfo
    - tmux
    - patchutils
    - zlib1g-dev
    - wget
    - bzip2
    - patch
    - vim-common
    - lbzip2
    - python
    - pkg-config
    - libglib2.0-dev
    - libpixman-1-dev
    - libssl-dev
    - makeself
    - unzip
    - p7zip-full

branches:
  only:
    - dev
    - master


before_install:
  - if [ -d "linux/.git" ]; then ls; else git clone --shallow-since=2020-04-01 https://github.com/torvalds/linux linux; fi
  - if [ -d "qemu/.git" ]; then ls; else git clone --shallow-since=2020-04-01 https://github.com/qemu/qemu qemu; fi
  - git submodule init -- linux
  - git submodule init -- qemu
  - git submodule update --depth=1 -- linux
  - git submodule update --depth=1 -- qemu
  - ./fast-setup.sh

jobs:
  include:
    - stage: cache warmup
      script: true
      after_failure:
        - ls -al
        - git submodule status
    - stage: build rv64 & test
      script:
        - source ./source.sh
        - mkdir build
        - cd build
        - cmake ../
        - travis_wait 120 make -j3
        - travis_wait 10 make run-tests
        - cd ..
      after_failure:
        - cat screenlog.0
        - cat output.log
    - stage: build (sifive)
      script:
        - source ./source.sh
        - mkdir build
        - cd build
        - cmake -DLINUX_SIFIVE=y -DSM_PLATFORM=sifive/fu540 ../
        - travis_wait 120 make -j3
        - cd ..
    - stage: build rv32 & test
      script:
        - BITS=32 ./fast-setup.sh
        - source source.sh
    - stage: build rv32 & test
      script:
        - BITS=32 ./fast-setup.sh
        - source source.sh
        - mkdir build32
        - cmake ../ -DRISCV32=y
        - travis_wait 120 make -j3
        - travis_wait 10 make run-tests
        - cd ..
