# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# prebuilt docker images with toolchain
executors:
  setup-rv64gc:
    docker:
      - image: keystoneenclaveorg/keystone:setup-rv64gc
  setup-rv32gc:
    docker:
      - image: keystoneenclaveorg/keystone:setup-rv32gc

# pre-defined commands
commands:
  setup-env:
    description: "Setup environment variables"
    steps:
      - run: source ./source.sh

jobs:
  build-and-test-rv64-qemu:
    executor: setup-rv64gc
    steps:
      - checkout
      - setup-env
      - run:
          name: "Build rv64 and run tests"
          command: |
              mkdir build
              cd build
              cmake ../
              make -j$(nproc)
              make run-tests
          no_output_timeout: 120m

workflows:
  rv64:
    jobs:
      - build-and-test-rv64-qemu
